/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.avscan;

import Database.Data;
import Database.DatabaseUtils;
import Database.MaintenanceData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.*;
import multi.use.frames.ShowCommentMaintenance;
import multi.use.frames.SmallErrorMessage;
import javax.swing.JDialog;

/**
 *
 * @author dmitr
 */
public class MaintenanceAddComment extends javax.swing.JFrame {

    private ConnectCallback connectCallback;
    private static final int MAX_CHARACTERS = 254;
    private MaintenanceData newMaint;

    public MaintenanceAddComment() {
        start();
    }
    

    public interface ConnectCallback {

        void onConnect();
    }

    public MaintenanceAddComment(Data data, ConnectCallback callback) {
        start();
        this.showEqID.setText(data.getEquipmentID());
        this.showEqName.setText(data.getEquipmentName());
        this.connectCallback = callback; // Save the callback instance
        createNowTimestamp();
        this.setVisible(true);
    }

    public void createNowTimestamp() {
        final SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        this.showDate.setText(format.format(timestamp));
    }

    private void start() {
        initComponents();

        // Attach DocumentFilter to limit character input
        ((AbstractDocument) inputArea.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text != null && (fb.getDocument().getLength() + text.length() - length) <= MAX_CHARACTERS) {
                    super.replace(fb, offset, length, text, attrs);
                    updateLimitNumber();
                }
            }
        });

        // Initialize the limit number
        updateLimitNumber();

        // Enable text wrapping and disable horizontal scrolling
        inputArea.setLineWrap(true);
        inputArea.setWrapStyleWord(true);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    }

    private void updateLimitNumber() {
        int remaining = MAX_CHARACTERS - inputArea.getDocument().getLength();
        limitNumber.setText(String.valueOf(remaining));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eqIDLabel = new javax.swing.JLabel();
        eqNameLabel = new javax.swing.JLabel();
        showEqID = new javax.swing.JLabel();
        showEqName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        charLimitLabel = new javax.swing.JLabel();
        limitNumber = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        receivedLabel = new javax.swing.JLabel();
        showDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        eqIDLabel.setText("Equipment ID:");

        eqNameLabel.setText("Equipment Name:");

        showEqID.setText("eqID");

        showEqName.setText("eqName");

        inputArea.setColumns(20);
        inputArea.setRows(5);
        jScrollPane1.setViewportView(inputArea);

        charLimitLabel.setText("Charcter limit:");

        limitNumber.setText("254");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        receivedLabel.setText("Received:");

        showDate.setText("date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addGap(18, 18, 18)
                        .addComponent(addButton)
                        .addGap(161, 161, 161))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eqIDLabel)
                                .addGap(34, 34, 34)
                                .addComponent(showEqID))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eqNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showDate)
                                    .addComponent(showEqName))))
                        .addContainerGap(343, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(charLimitLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limitNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(receivedLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqIDLabel)
                    .addComponent(showEqID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqNameLabel)
                    .addComponent(showEqName))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receivedLabel)
                    .addComponent(showDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charLimitLabel)
                    .addComponent(limitNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(backButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        boolean inserted = false;
        if (this.inputArea.getText().length() < 1) {
            new SmallErrorMessage("Please input what happened with the equipment.", this).setVisible(true);
            return;
        }

        try {
            DatabaseUtils insert = new DatabaseUtils();
            inserted = insert.newInsertIntoMaintenanceTable(this.showEqID.getText(), this.inputArea.getText(), this.showDate.getText());
        } catch (SQLException ex) {
            new SmallErrorMessage("Database connection error!", this).setVisible(true);
        }
        if (connectCallback != null) {
            connectCallback.onConnect();
            
            //Just confirmation! NOT error
            new SmallErrorMessage("Successfully added "+this.toString(),this).setVisible(true);//Just confiramtion
            this.dispose();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    
    @Override
    public String toString() {
        return "{" + "Equipment ID: " + showEqID.getText() + ", Equipment Name: " + showEqName.getText()
                + ", Received date: " + showDate.getText() + '}';
    }


    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        connectCallback.onConnect();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        connectCallback.onConnect();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintenanceAddComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintenanceAddComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintenanceAddComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintenanceAddComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaintenanceAddComment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel charLimitLabel;
    private javax.swing.JLabel eqIDLabel;
    private javax.swing.JLabel eqNameLabel;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel limitNumber;
    private javax.swing.JLabel receivedLabel;
    private javax.swing.JLabel showDate;
    private javax.swing.JLabel showEqID;
    private javax.swing.JLabel showEqName;
    // End of variables declaration//GEN-END:variables
}
